#file: noinspection YAMLSchemaValidation
name: Deploy App Engine

on:
    push:
        branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            -   uses: 'actions/checkout@v3'
            -   uses: 'google-github-actions/auth@v1'
                with:
                    workload_identity_provider: 'projects/298427231839/locations/global/workloadIdentityPools/helpers-api/providers/github'
                    service_account: 'app-engine-helpers-api@helpers-api-376915.iam.gserviceaccount.com'
            -   uses: 'google-github-actions/deploy-appengine@v1'
